#!/bin/bash
# Aurthor : Sumit pawar
# Created date : 26 April 2020
# Modified date : 26 April 2020
# Description : This script will check the file status as file empty or non-empty

echo
echo Scripts begins from here, please provide the required inputs
echo
echo Please provide the Absolute path of file
read path
echo please provide the accurate file name
read filename
echo
	if [ -s $path/$filename ]
	then
		echo File exist and is not empty
	elif [ -e $path/$filename ]
	then
		echo File exist but empty
	else
		echo file does not exist
	fi
echo
echo Script ends here...Thanks for your input
