#!/bin/bash
# Aurthor : Sumit pawar
# Created date : 26 April 2020
# Modified date : 26 April 2020
# Dsecription : This script will check the file status exist on given location or not

echo
echo Script begins from here, checking the file status
echo
echo please provide the Aboslute path of file
read path
echo please provide the file name
read filename
echo
	if [ -e $path/$filename ]
	then
		echo file exist
	else
		echo file does not exist
	fi
echo
echo Script ends here
