#!/bin/bash
# Author : Sumit Pawar
# Created Date : 3 April 2020
# Description : This Script will check status of remote host IP from our machine
# Modified Date : 3 April 2020

echo Script begins from here
echo
hosts='/home/hadoop/scripts/host_list'

for ip in $(cat $hosts)
do
	ping -c1 $ip &> /dev/null
	if [ $? -eq 0 ]
	then
	echo $ip is OK
	else
	echo $ip is NOT OK
	fi
done
